# Generated by cpp11: do not edit by hand

agg_array_sum <- function(x, codes, out_sizes) {
  .Call(`_teems_agg_array_sum`, x, codes, out_sizes)
}

har_split_records <- function(cf) {
  .Call(`_teems_har_split_records`, cf)
}

har_payload_concat <- function(records, offset) {
  .Call(`_teems_har_payload_concat`, records, offset)
}

har_payload_f32 <- function(records, offset, n) {
  .Call(`_teems_har_payload_f32`, records, offset, n)
}

har_payload_i32 <- function(records, offset, n) {
  .Call(`_teems_har_payload_i32`, records, offset, n)
}

har_spse_fill <- function(records, offset, n) {
  .Call(`_teems_har_spse_fill`, records, offset, n)
}

har_fixed_width_strings <- function(bytes, width, trim) {
  .Call(`_teems_har_fixed_width_strings`, bytes, width, trim)
}

parse_solution_meta <- function(path_prefix) {
  .Call(`_teems_parse_solution_meta`, path_prefix)
}

parse_solution_bins <- function(path_prefix, names_filter) {
  .Call(`_teems_parse_solution_bins`, path_prefix, names_filter)
}
