#' @title Configure and solve model
#' @export
#' @description Calls the
#'   \href{https://github.com/teemsphere/teems-solver}{teems-solver}
#'   Docker image to solve the constrained optimization problem.
#'   Runs singularity, accuracy, and error checks on the results
#'   and structures outputs with [`ems_compose()`].
#' @param cmf_path Character length 1, path to the CMF file
#'   generated by [`ems_deploy()`].
#' @param solution_method The solution method to be used, default
#'   is the one-step `"Johansen"`. Choices:
#'   * `"Johansen"`: The Johansen method is fast however it should
#'   only be used as a rough approximation due to handling of
#'   nonlinear equations. See:
#'   \href{https://www.copsmodels.com/gpmanual.htm#gpd1.2.13}{Johansen}
#'   * `"mod_midpoint"`: The modified midpoint method
#'   performs multiple passes. See: \href{https://www.copsmodels.com/gpmanual.htm#gpd3.12.2}{modified
#'   midpoint}
#' @param matrix_method Character of length 1, matrix solution
#'   method (default is `"auto"`). Choices:
#'   * `"auto"`: Selects the method from the model type and size
#'   (see Details). The selection is reported at run time.
#'   * `"LU"`: Standard LU decomposition, the most robust and
#'   potentially slowest for a large model. For use with both
#'   static and dynamic models.
#'   * `"DBBD"`: Doubly bordered block diagonal, parallel solution
#'   method for static models. Potentially faster than `"LU"`
#'   although less robust.
#'   * `"SBBD"`: Singly bordered block diagonal, parallel solution
#'   method for intertemporal models. Potentially faster than
#'   `"LU"` although less robust.
#'   * `"NDBBD"`: Nested doubly bordered block diagonal, parallel
#'   solution method for large intertemporal models with many
#'   timesteps.
#' @param n_subintervals Integer length 1 (default is `1L`),
#'   number of subintervals for the applied shock. More
#'   subintervals may alleviate accuracy issues stemming from
#'   large shock magnitudes.
#' @param steps Integer length 3 (default is `c(2L, 4L, 8L)`). A
#'   vector of steps for the modified midpoint method, must be
#'   all odd or all even and length 3. A larger number of steps
#'   may improve accuracy for some model runs.
#' @param n_tasks Integer length 1 (default is `1L`), number of
#'   tasks to run in parallel. Must be `1L` if `"matrix_method"`
#'   == "LU".
#' @param laA Integer length 1 (default is `300L`). Memory
#'   parameter (%) for `"LU"` and `"SBBD"`.
#' @param laD Integer length 1 (default is `200L`). Memory
#'   parameter (%) for `"DBBD"` and `"NDBBD"`.
#' @param laDi Integer length 1 (default is `500L`). Memory
#'   parameter (%) for `"NDBBD"` only.
#' @details `matrix_method = "auto"` selects `"SBBD"` for
#'   intertemporal models (fastest on every benchmarked shape,
#'   including single-task runs) and `"LU"` for static models,
#'   switching to `"DBBD"` when `n_tasks >= 2` and the deployed
#'   system is large (roughly 2 million or more equations, or 1.5
#'   million with 100+ regions). The selection is reported at run
#'   time; set `matrix_method` explicitly to override it. Runs
#'   without deploy metadata (e.g. [`solve_in_situ()`]) fall back
#'   to `"LU"` for static models regardless of size.
#'
#'   Increase `laA`, `laD`, or `laDi` gradually if the
#'   solver returns "Error return from MA48B/BD because LA is
#'   ...". The relevant parameter depends on the `matrix_method`
#'   in use (see above).
#' @param suppress_outputs Logical length 1 (default is `FALSE`).
#'   When `TRUE` solver outputs are not automatically converted
#'   into structured data with [`ems_compose()`].
#' @param terminal_run Logical length 1 (default is `FALSE`).
#'   When `TRUE`, the function is exited without running the
#'   solver. This allows the user to close any R IDE or other
#'   programs prior to running from the terminal. When `TRUE`
#'   solver outputs are not automatically converted into
#'   structured data with [`ems_compose()`].
#' @param append_args Character vector (default `NULL`).
#'   Additional arguments appended to the Docker run command
#'   (e.g., `c("-smllthreads 2", "-maxthreads 2")`).
#' @seealso [`ems_deploy()`] for generating `"cmf_path"`.
#'   [`solve_in_situ()`] for calling the solver on existing input
#'   files. [`ems_compose()`] for structuring data when
#'   `"suppress_outputs"` or `"terminal_run"` is `TRUE`.
#' @return A tibble of model output variables and coefficients.
#'   `invisible(NULL)` if `suppress_outputs = TRUE`. Instructions
#'   for terminal execution if `terminal_run = TRUE`.
#' @examples
#' \dontrun{
#' # The following examples require the teems solver to be built. 
#' # See https://teemsphere.github.io/ to get started.
#'  
#' # Solving a static model with Johansen:
#' ems_solve(cmf_path)
#' 
#' # Solving a dynamic model with the SBBD method:
#' ems_solve(cmf_path,
#'           solution_method = "mod_midpoint",
#'           matrix_method = "SBBD",
#'           n_tasks = 6)
#' }
ems_solve <- function(cmf_path,
                      solution_method = c("Johansen", "mod_midpoint"),
                      matrix_method = c("auto", "LU", "DBBD", "SBBD", "NDBBD"),
                      n_subintervals = 1L,
                      steps = c(2L, 4L, 8L),
                      n_tasks = 1L,
                      laA = 300L,
                      laD = 200L,
                      laDi = 500L,
                      suppress_outputs = FALSE,
                      terminal_run = FALSE,
                      append_args = NULL
) {
if (missing(cmf_path)) {
  .cli_missing(cmf_path)
}
args_list <- mget(names(formals()))
call <- match.call()
output <- .implement_solve(
  args_list = args_list,
  call = call
)
if (is.null(output)) invisible(output) else output
}
