#' @title Validate and write all model inputs
#' @export
#' @description Validates all data and model inputs, processes
#'   shocks and closure swaps, and writes the input files
#'   required by [`ems_solve()`].
#' @return Path to the CMF file, to be passed to [`ems_solve()`].
#' @param .data A list of data.tables generated by
#'   [`ems_data()`].
#' @param model A tibble generated by [`ems_model()`].
#' @param shock A `shock` object or list of `shock` objects
#'   produced by [`ems_uniform_shock()`], [`ems_custom_shock()`],
#'   or [`ems_scenario_shock()`]. When `NULL` (default), no shock
#'   is applied and input data is returned without change.
#' @param swap_in A character vector of variable length, list
#'   generated by [`ems_swap()`], or combination of the above
#'   provided as a list (default `NULL`). Variables to be made
#'   exogenous.
#' @param swap_out A character vector of variable length, list
#'   generated by [`ems_swap()`], or combination of the above
#'   provided as a list (default `NULL`). Variables to be made
#'   endogenous.
#' @param shock_file A character vector length 1 (default
#'   `NULL`). Path to a file with .shf extension representing a
#'   fully prepared shock file. No checks or modifications are
#'   carried out on this file.
#' @param write_coefficients Logical of length 1 (default `FALSE`).
#'   Coefficient values return to R through the solver's binary
#'   coefficient dump, read selectively by [`ems_compose()`]. Set
#'   `TRUE` to also emit the GEMPACK-style per-coefficient CSV files
#'   (`out/coefficients/`, `out/postsim/`) via auto-generated
#'   `File`/`Write` statements, e.g. for inspection outside R.
#' @seealso [`ems_data()`] for loading and preparing data inputs.
#'   [`ems_model()`] for parsing and modifying model and closure
#'   files. [`ems_uniform_shock()`], [`ems_custom_shock()`], and
#'   [`ems_scenario_shock()`] for preparing shocks.
#'   [`ems_swap()`] for preparing closure swaps. [`ems_solve()`]
#'   for utilizing the output of this function.
#' @examples
#' \dontrun{
#' # The following examples require input data. See
#' # https://teemsphere.github.io/ to get started.
#'
#' # Uniform shock applied to full variable with value 1
#' shock <- ems_uniform_shock("qfd", value = 1)
#'
#' # Full variable swap, qfd for tfd
#' cmf_path <- ems_deploy(
#'   .data = dat,
#'   model = model,
#'   shock = shock,
#'   swap_in = "qfd",
#'   swap_out = "tfd"
#' )
#'
#' # Partial variable swap (element "row" of set REG with index r)
#' yp_row <- ems_swap("yp", REGr = "row")
#' dppriv_row <- ems_swap("dppriv", REGr = "row")
#'
#' # Swap part of yp for part of dppriv; qfd for tfd
#' cmf_path <- ems_deploy(
#'  .data = dat,
#'  model = model,
#'  shock = shock,
#'  swap_in = list(yp_row, "qfd"),
#'  swap_out = list(dppriv_row, "tfd")
#' )
#' }
ems_deploy <- function(.data,
                       model,
                       shock = NULL,
                       swap_in = NULL,
                       swap_out = NULL,
                       shock_file = NULL,
                       write_coefficients = FALSE
) {
if (missing(.data)) {
  .cli_missing(.data)
}
if (missing(model)) {
  .cli_missing(model)
}
call <- match.call()
args_list <- mget(names(formals()))
cmf_path <- .finalize(
  args_list = args_list,
  call = call
)
cmf_path
}