#' @title Configure and solve model
#' @export
#' @description Calls the
#'   \href{https://github.com/teemsphere/teems-solver}{teems-solver}
#'   Docker image to solve the constrained optimization problem.
#'   Runs singularity, accuracy, and error checks on the results
#'   and structures outputs with [`ems_compose()`].
#' @param cmf_path Character length 1, path to the CMF file
#'   generated by [`ems_deploy()`].
#' @param solution_method The solution method to be used, default
#'   is the one-step `"Johansen"`. Choices:
#'   * `"Johansen"`: The Johansen method is fast however it should
#'   only be used as a rough approximation due to handling of
#'   nonlinear equations. See:
#'   \href{https://www.copsmodels.com/gpmanual.htm#gpd1.2.13}{Johansen}
#'   * `"Gragg"`: Gragg's method (the smoothed modified midpoint
#'   method; Pearson 1991). The shock is applied over a sequence
#'   of linearized steps — an Euler first step, midpoint
#'   "leapfrog" steps, and a terminal smoothing pass — and the
#'   sequence is repeated for each of the three step counts in
#'   `steps`. The three solutions are then combined by Richardson
#'   extrapolation, giving rapid error decay as steps increase
#'   plus an accuracy estimate from the agreement between levels.
#'   Recommended whenever accuracy matters. See also:
#'   \href{https://www.copsmodels.com/gpmanual.htm#gpd3.12.2}{GEMPACK
#'   solution methods}
#'   * `"Euler"`: The forward Euler method, computed for each of
#'   the three step counts in `steps` and combined by Richardson
#'   extrapolation. Converges more slowly than `"Gragg"` (its
#'   truncation error shrinks linearly in the step size, so the
#'   extrapolated accuracy gains one order per solution instead of
#'   two) but it is the most robust of the multistep methods: each
#'   step uses only the current state, so it tolerates
#'   near-asymptote levels and severe shocks — including exact
#'   `-100%` shocks — where the midpoint family can become
#'   unstable. Any strictly increasing step counts are permitted.
#' @param matrix_method Character of length 1, matrix solution
#'   method (default is `"auto"`). Choices:
#'   * `"auto"`: Selects the method from the model type and size
#'   (see Details). The selection is reported at run time.
#'   * `"LU"`: Standard LU decomposition, the most robust and
#'   potentially slowest for a large model. For use with both
#'   static and dynamic models.
#'   * `"DBBD"`: Doubly bordered block diagonal, parallel solution
#'   method for static models. Potentially faster than `"LU"`
#'   although less robust.
#'   * `"SBBD"`: Singly bordered block diagonal, parallel solution
#'   method for intertemporal models. Potentially faster than
#'   `"LU"` although less robust.
#'   * `"NDBBD"`: Nested doubly bordered block diagonal, parallel
#'   solution method for large intertemporal models with many
#'   timesteps.
#' @param n_subintervals Integer length 1 (default is `1L`),
#'   number of subintervals for the applied shock. More
#'   subintervals may alleviate accuracy issues stemming from
#'   large shock magnitudes.
#' @param steps Integer length 3 (default is `c(2L, 4L, 8L)`). A
#'   strictly increasing vector of step counts for the three
#'   extrapolation solutions of the `"Gragg"` and `"Euler"`
#'   methods. A larger number of steps may improve accuracy for
#'   some model runs. For `"Gragg"` all three must additionally be
#'   even, because the error-cancellation theory behind the
#'   extrapolation assumes even step counts (Pearson 1991,
#'   Theorem 6.1); `"Euler"` has no parity requirement. Ignored
#'   when `solution_method = "Johansen"`.
#' @param n_tasks Integer length 1 (default is `1L`), number of
#'   tasks to run in parallel. Must be `1L` if `"matrix_method"`
#'   == "LU".
#' @param laA Integer length 1 (default is `300L`). Memory
#'   parameter (%) for `"LU"` and `"SBBD"`.
#' @param laD Integer length 1 (default is `200L`). Memory
#'   parameter (%) for `"DBBD"` and `"NDBBD"`.
#' @param laDi Integer length 1 (default is `500L`). Memory
#'   parameter (%) for `"NDBBD"` only.
#' @param inmemory Logical length 1 or `NULL` (default). When
#'   `TRUE`, the solver keeps value arrays and block factors
#'   resident in memory instead of spilling them to scratch
#'   files; when `FALSE`, scratch files are used. The default
#'   (`NULL`) lets the solver choose per matrix method (currently
#'   in-memory for all methods except `"NDBBD"`). The solver
#'   falls back to scratch files with a warning if the estimated
#'   memory requirement exceeds what is available.
#' @param verbosity Integer length 1 (`0`, `1`, or `2`) or `NULL`
#'   (default, equivalent to the solver default of `1`). Solver
#'   log detail: `0` restricts output to errors, warnings, and
#'   the accuracy summary; `1` adds phase progress and timings;
#'   `2` adds per-rank and per-block debug detail.
#' @details `matrix_method = "auto"` selects `"SBBD"` for
#'   intertemporal models (fastest on every benchmarked shape,
#'   including single-task runs) and `"LU"` for static models,
#'   switching to `"DBBD"` when `n_tasks >= 2` and the deployed
#'   system is large (roughly 2 million or more equations, or 1.5
#'   million with 100+ regions). The selection is reported at run
#'   time; set `matrix_method` explicitly to override it. Runs
#'   without deploy metadata (e.g. [`solve_in_situ()`]) fall back
#'   to `"LU"` for static models regardless of size.
#'
#'   Increase `laA`, `laD`, or `laDi` gradually if the
#'   solver returns "Error return from MA48B/BD because LA is
#'   ...". The relevant parameter depends on the `matrix_method`
#'   in use (see above).
#' @param suppress_outputs Logical length 1 (default is `FALSE`).
#'   When `TRUE` solver outputs are not automatically converted
#'   into structured data with [`ems_compose()`].
#' @param terminal_run Logical length 1 (default is `FALSE`).
#'   When `TRUE`, the function is exited without running the
#'   solver. This allows the user to close any R IDE or other
#'   programs prior to running from the terminal. When `TRUE`
#'   solver outputs are not automatically converted into
#'   structured data with [`ems_compose()`].
#' @param append_args Character vector (default `NULL`).
#'   Additional arguments appended to the Docker run command
#'   (e.g., `c("-smllthreads 2", "-maxthreads 2")`).
#' @seealso [`ems_deploy()`] for generating `"cmf_path"`.
#'   [`solve_in_situ()`] for calling the solver on existing input
#'   files. [`ems_compose()`] for structuring data when
#'   `"suppress_outputs"` or `"terminal_run"` is `TRUE`.
#' @return A tibble of model output variables and coefficients.
#'   `invisible(NULL)` if `suppress_outputs = TRUE`. Instructions
#'   for terminal execution if `terminal_run = TRUE`.
#' @references Pearson, K.R. (1991), "Solving Nonlinear Economic
#'   Models Accurately via a Linear Representation", Impact
#'   Project Preliminary Working Paper No. IP-55, Monash
#'   University (revised June 2002).
#' @examples
#' \dontrun{
#' # The following examples require the teems solver to be built. 
#' # See https://teemsphere.github.io/ to get started.
#'  
#' # Solving a static model with Johansen:
#' ems_solve(cmf_path)
#' 
#' # Solving a dynamic model with the SBBD method:
#' ems_solve(cmf_path,
#'           solution_method = "Gragg",
#'           matrix_method = "SBBD",
#'           n_tasks = 6)
#' }
ems_solve <- function(cmf_path,
                      solution_method = c("Johansen", "Gragg", "Euler"),
                      matrix_method = c("auto", "LU", "DBBD", "SBBD", "NDBBD"),
                      n_subintervals = 1L,
                      steps = c(2L, 4L, 8L),
                      n_tasks = 1L,
                      laA = 300L,
                      laD = 200L,
                      laDi = 500L,
                      inmemory = NULL,
                      verbosity = NULL,
                      suppress_outputs = FALSE,
                      terminal_run = FALSE,
                      append_args = NULL
) {
if (missing(cmf_path)) {
  .cli_missing(cmf_path)
}
args_list <- mget(names(formals()))
call <- match.call()
output <- .implement_solve(
  args_list = args_list,
  call = call
)
if (is.null(output)) invisible(output) else output
}
