#' @title Configure and solve model
#' @export
#' @description Calls the
#'   \href{https://github.com/teemsphere/teems-solver}{teems-solver}
#'   Docker image to solve the constrained optimization problem.
#'   Runs singularity, accuracy, and error checks on the results
#'   and structures outputs with [`ems_compose()`].
#' @param cmf_path Character length 1, path to the CMF file
#'   generated by [`ems_deploy()`].
#' @param solution_method The solution method to be used, default
#'   is the one-step `"Johansen"`. Choices:
#'   * `"Johansen"`: The Johansen method is fast however it should
#'   only be used as a rough approximation due to handling of
#'   nonlinear equations. See:
#'   \href{https://www.copsmodels.com/gpmanual.htm#gpd1.2.13}{Johansen}
#'   * `"Gragg"`: Gragg's method (the smoothed modified midpoint
#'   method; Pearson 1991). The shock is applied over a sequence
#'   of linearized steps — an Euler first step, midpoint
#'   "leapfrog" steps, and a terminal smoothing pass — and the
#'   sequence is repeated for each of the three step counts in
#'   `steps`. The three solutions are then combined by Richardson
#'   extrapolation, giving rapid error decay as steps increase
#'   plus an accuracy estimate from the agreement between levels.
#'   Recommended whenever accuracy matters. See also:
#'   \href{https://www.copsmodels.com/gpmanual.htm#gpd3.12.2}{GEMPACK
#'   solution methods}
#'   * `"Euler"`: The forward Euler method, computed for each of
#'   the three step counts in `steps` and combined by Richardson
#'   extrapolation. Converges more slowly than `"Gragg"` (its
#'   truncation error shrinks linearly in the step size, so the
#'   extrapolated accuracy gains one order per solution instead of
#'   two) but it is the most robust of the multistep methods: each
#'   step uses only the current state, so it tolerates
#'   near-asymptote levels and severe shocks — including exact
#'   `-100%` shocks — where the midpoint family can become
#'   unstable. Any strictly increasing step counts are permitted.
#'   * `"RK2"`, `"RK4"`: Explicit Runge-Kutta methods (the midpoint
#'   method and the classic fourth-order method; Schiffmann 2022).
#'   A single solution is computed with the one step count in
#'   `steps` — no Richardson extrapolation — with each step built
#'   from 2 (`"RK2"`) or 4 (`"RK4"`) staged linear solves. `"RK4"`
#'   reaches a given accuracy in far fewer steps than the
#'   extrapolating methods.
#'   * `"BoSha32"`, `"DoPri54"`: Embedded Runge-Kutta pairs
#'   (Bogacki-Shampine 3(2), 4 stages; Dormand-Prince 5(4), 7
#'   stages). Alongside the solution they compute a
#'   component-by-component estimate of the cumulative error —
#'   returned as the `error_metric` column by [`ems_compose()`]
#'   and summarized as a face value in the solver log — and they
#'   support adaptive step-size control via `adaptive` and
#'   `eps_tolerance`. `"DoPri54"` with `adaptive = "yes"` is the
#'   recommended high-accuracy choice.
#' @param matrix_method Character of length 1, matrix solution
#'   method (default is `"auto"`). Choices:
#'   * `"auto"`: Selects the method from the model type and size
#'   (see Details). The selection is reported at run time.
#'   * `"LU"`: Standard LU decomposition, the most robust and
#'   potentially slowest for a large model. For use with both
#'   static and dynamic models.
#'   * `"DBBD"`: Doubly bordered block diagonal, parallel solution
#'   method for static models. Potentially faster than `"LU"`
#'   although less robust.
#'   * `"SBBD"`: Singly bordered block diagonal, parallel solution
#'   method for intertemporal models. Potentially faster than
#'   `"LU"` although less robust.
#'   * `"NDBBD"`: Nested doubly bordered block diagonal, parallel
#'   solution method for large intertemporal models with many
#'   timesteps.
#' @param n_subintervals Integer length 1 (default is `1L`),
#'   number of subintervals for the applied shock. More
#'   subintervals may alleviate accuracy issues stemming from
#'   large shock magnitudes.
#' @param steps Integer length 3 (default is `c(2L, 4L, 8L)`). A
#'   strictly increasing vector of step counts for the three
#'   extrapolation solutions of the `"Gragg"` and `"Euler"`
#'   methods. A larger number of steps may improve accuracy for
#'   some model runs. For `"Gragg"` all three must additionally be
#'   even, because the error-cancellation theory behind the
#'   extrapolation assumes even step counts (Pearson 1991,
#'   Theorem 6.1); `"Euler"` has no parity requirement. The
#'   Runge-Kutta methods compute a single solution and instead
#'   take one step count (e.g. `steps = 8L`), which under
#'   `adaptive` control is the initial step count only. Ignored
#'   when `solution_method = "Johansen"`.
#' @param ... Additional named solver arguments; anything else is an
#'   error, never a silently ignored flag. Three groups are accepted:
#'   the Runge-Kutta step controls (`adaptive`, `eps_tolerance`,
#'   `max_retries`, `retry_adjust`; see [`ems_RK()`] for their
#'   documentation and RK-tuned defaults); the MA48 workspace initial
#'   guesses `laA`, `laD` and `laDi` (integer percents of the system
#'   nonzeros — `laA` for `"LU"`/`"SBBD"` and the diagonal blocks,
#'   `laD` for the `"DBBD"`/`"NDBBD"` interface systems, `laDi` for
#'   `"NDBBD"` intermediate interfaces; when omitted, a previous run
#'   of the same deployment warm-starts them from its recorded
#'   `la_used` in `sol.stats.json`, else package defaults apply, and
#'   the solver grows the workspace itself if any guess proves too
#'   small); and the expert solver flags `fastrefac` (persistent-pivot
#'   refactorization, logical), `gpzerodivide` (GEMPACK dual-class
#'   ZERODIVIDE semantics, logical), `cntl_3`/`cntl_6` (HSL
#'   pivot/ordering thresholds, numeric), `nsbbdblocks` (SBBD
#'   block-count override, integer), `withmc66` (MC66 row ordering
#'   for SBBD, logical), `smllthreads` (OpenMP threads for small
#'   sections, integer), `tempdir` (container-side scratch directory,
#'   character), `nowrites` (skip the solver-side output-file
#'   dumps, logical; coefficient composition then has nothing to read
#'   — distinct from `suppress_outputs`, which only skips the R-side
#'   composition) and `condest` (per-solve quality diagnostics on the
#'   `"LU"` matrix method, logical: componentwise backward error and
#'   scaled condition numbers via HSL MA60/MC71, logged per linear
#'   solve with run maxima recorded under `condest` in
#'   `sol.stats.json`; diagnostic-only — solutions are unchanged —
#'   and informative only for nonzero shocks). Effective values of
#'   recorded flags land in `sol.stats.json` regardless of how they
#'   were passed.
#' @param n_threads Integer length 1 (default `1L`), OpenMP threads
#'   per MPI task. Results with more than one thread are numerically
#'   equivalent but not bit-reproducible across thread counts
#'   (parallel reduction order).
#' @param precision Character length 1, `"single"` (default) or
#'   `"double"`: floating-point precision of the solver's coefficient
#'   storage. `"single"` halves memory traffic and suffices for
#'   ordinary step counts. `"double"` selects the double-precision
#'   solver binary shipped in the same image, removing the
#'   single-precision update-rounding floor that deep extrapolation
#'   ladders and many-step large-shock runs otherwise converge onto
#'   (per-pass rounding accumulates with step count, so beyond the
#'   floor extra steps stop helping). Roughly doubles
#'   coefficient-array memory. The effective precision is recorded in
#'   `sol.stats.json` and the model diagnostics solve record.
#' @param n_tasks Integer length 1 (default is `1L`), number of
#'   tasks to run in parallel. Must be `1L` if `"matrix_method"`
#'   == "LU".
#' @param inmemory Logical length 1 or `NULL` (default). When
#'   `TRUE`, the solver keeps value arrays and block factors
#'   resident in memory instead of spilling them to scratch
#'   files; when `FALSE`, scratch files are used. The default
#'   (`NULL`) lets the solver choose per matrix method (currently
#'   in-memory for all methods except `"NDBBD"`). The solver
#'   falls back to scratch files with a warning if the estimated
#'   memory requirement exceeds what is available.
#' @param verbosity Integer length 1 (`0`, `1`, or `2`) or `NULL`
#'   (default, equivalent to the solver default of `1`). Solver
#'   log detail: `0` restricts output to errors, warnings, and
#'   the accuracy summary; `1` adds phase progress and timings;
#'   `2` adds per-rank and per-block debug detail.
#' @details `matrix_method = "auto"` selects `"SBBD"` for
#'   intertemporal models (fastest on every benchmarked shape,
#'   including single-task runs) and `"LU"` for static models,
#'   switching to `"DBBD"` when `n_tasks >= 2`, the deployed system
#'   is large (roughly 2 million or more equations, or 1.5 million
#'   with 100+ diagonal blocks) and the solver's structural probe of
#'   the deployment finds a block partition with at least `n_tasks`
#'   blocks and a border below a tenth of the system. The probe (a
#'   sub-second run on small models; the same run `pre_probe` uses,
#'   never launched twice) is skipped when the deploy metadata already
#'   settles the choice: static single-task runs and static systems
#'   below 1.5 million equations resolve to `"LU"` without it. When it
#'   runs, its evidence -- chain dimension, chosen partition, block
#'   count and border share -- is reported with the selection and
#'   written, together with the threshold values used, into
#'   `model_diagnostics.txt`. A model that declares intertemporal sets
#'   but couples no equation through lead/lag offsets is measured as
#'   static. The thresholds are calibrated on 1-4 task benchmarks;
#'   the `"SBBD"` to `"NDBBD"` escalation is plumbed but disabled
#'   until measured. Set `matrix_method` explicitly to override the
#'   selection. Runs without deploy metadata (e.g.
#'   [`solve_in_situ()`]) probe when `n_tasks >= 2` and take the
#'   system size from the probe.
#'
#'   Condensation interacts with that choice. Backsolving (see the
#'   `backsolve` argument of [`ems_model()`]) substitutes variables
#'   out of the system, which densifies the diagonal blocks the
#'   bordered methods exploit: it pays under `"LU"` on static models
#'   and costs wall time everywhere else. A condensed deployment
#'   solved with a bordered method, or any condensed intertemporal
#'   deployment, is flagged at run time. Omission (`omit`) does not
#'   densify anything and is never flagged.
#'
#'   The MA48 workspace sizes (`laA`, `laD`, `laDi`) never need
#'   manual tuning: the solver reallocates and retries on a
#'   too-small workspace, logging each growth, and records the
#'   effective sizes as `la_used` in `sol.stats.json`, which later
#'   runs of the same deployment reuse as their starting point. Pass
#'   them through `...` only to pin a specific starting size.
#' @param suppress_outputs Logical length 1 (default is `FALSE`).
#'   When `TRUE` solver outputs are not automatically converted
#'   into structured data with [`ems_compose()`].
#' @param terminal_run Logical length 1 (default is `FALSE`).
#'   When `TRUE`, the function is exited without running the
#'   solver. This allows the user to close any R IDE or other
#'   programs prior to running from the terminal. When `TRUE`
#'   solver outputs are not automatically converted into
#'   structured data with [`ems_compose()`].
#' @param assertions Character length 1, `"fatal"`, `"warn"` or
#'   `"off"` (default `NULL`, solver default `"fatal"`). Severity of
#'   TAB `Assertion` statement failures (GEMPACK manual 25.3):
#'   `"warn"` reports and continues, `"off"` skips the checks.
#' @param range_test_initial Character length 1, `"fatal"`, `"warn"`
#'   or `"off"` (default `NULL`, solver default `"warn"`). Severity of
#'   declared-range violations (e.g. `(ge 0)`) on initial values
#'   (GEMPACK manual 25.4.4).
#' @param range_test_updated Character length 1, `"fatal"`, `"warn"`
#'   or `"off"` (default `NULL`, solver default `"warn"`). As
#'   `range_test_initial`, for updated values.
#' @param postsim Logical length 1 (default `NULL`, solver default
#'   `TRUE`). `FALSE` skips the TAB's `PostSim` sections.
#' @param complementarity A `teems_complementarity` object built by
#'   [`ems_complementarity()`] (default is `NULL`), run controls for
#'   models with active `Complementarity` statements (GEMPACK manual
#'   ch. 51). `NULL` applies the solver defaults; ignored by the
#'   solver when the model has no active complementarity component.
#' @param pre_probe Logical length 1 (default `FALSE`). When `TRUE`,
#'   run the solver's structural probe first and abort — with the
#'   defective variable and equation elements named — if the deployed
#'   system is structurally singular, instead of failing mid-solve
#'   with an unnamed singularity. Adds a probe run's cost (the
#'   pre-solve pipeline plus a maximum matching: negligible below
#'   ~10^5 equations, tens of seconds around 10^6); with
#'   `matrix_method = "auto"` the same probe run also supplies the
#'   structural evidence for the method choice. See [`ems_probe()`]
#'   for the full diagnosis.
#' @seealso [`ems_deploy()`] for generating `"cmf_path"`.
#'   [`solve_in_situ()`] for calling the solver on existing input
#'   files. [`ems_compose()`] for structuring data when
#'   `"suppress_outputs"` or `"terminal_run"` is `TRUE`.
#' @return A tibble of model output variables and coefficients.
#'   `invisible(NULL)` if `suppress_outputs = TRUE`. Instructions
#'   for terminal execution if `terminal_run = TRUE`.
#' @references Pearson, K.R. (1991), "Solving Nonlinear Economic
#'   Models Accurately via a Linear Representation", Impact
#'   Project Preliminary Working Paper No. IP-55, Monash
#'   University (revised June 2002).
#'
#'   Schiffmann, F. (2022), "Runge Kutta integrators for fast and
#'   accurate solutions in GEMPACK".
#' @examples
#' \dontrun{
#' # The following examples require the teems solver to be built. 
#' # See https://teemsphere.github.io/ to get started.
#'  
#' # Solving a static model with Johansen:
#' ems_solve(cmf_path)
#' 
#' # Solving a dynamic model with the SBBD method:
#' ems_solve(cmf_path,
#'           solution_method = "Gragg",
#'           matrix_method = "SBBD",
#'           n_tasks = 6)
#' }
ems_solve <- function(cmf_path,
                      solution_method = c("Johansen", "Gragg", "Euler", "RK2", "RK4", "BoSha32", "DoPri54"),
                      matrix_method = c("auto", "LU", "DBBD", "SBBD", "NDBBD"),
                      n_subintervals = 1L,
                      steps = c(2L, 4L, 8L),
                      n_tasks = 1L,
                      n_threads = 1L,
                      precision = c("single", "double"),
                      inmemory = NULL,
                      verbosity = NULL,
                      suppress_outputs = FALSE,
                      terminal_run = FALSE,
                      assertions = NULL,
                      range_test_initial = NULL,
                      range_test_updated = NULL,
                      postsim = NULL,
                      complementarity = NULL,
                      pre_probe = FALSE,
                      ...
) {
if (missing(cmf_path)) {
  .cli_missing(cmf_path)
}
call <- match.call()
# Named extras ride through the dots: the Runge-Kutta step controls
# (ems_RK() is the documented front end), the MA48 workspace initial
# guesses and the expert solver flags. Anything else here is an
# error, never silently ignored.
rk_args <- list(
  adaptive = c("no", "yes", "accuracy-only"),
  eps_tolerance = 0.1,
  max_retries = NULL,
  retry_adjust = NULL
)
xtr_args <- .solver_extra_args()
dots <- list(...)
unknown_args <- setdiff(names(dots), c(names(rk_args), names(xtr_args)))
if (length(dots) &&
  (is.null(names(dots)) || !all(nzchar(names(dots))) || length(unknown_args))) {
  if (!length(unknown_args)) unknown_args <- "<unnamed>"
  .cli_action(solve_err$solver_dots,
    action = c("abort", "inform"),
    call = call
  )
}
for (nm in names(dots)) {
  if (nm %in% names(rk_args)) {
    rk_args[nm] <- dots[nm]
  } else {
    xtr_args[nm] <- dots[nm]
  }
}
args_list <- c(mget(setdiff(names(formals()), "...")), rk_args, xtr_args)
output <- .implement_solve(
  args_list = args_list,
  call = call
)
if (is.null(output)) invisible(output) else output
}
